auth.type: InMemory
auth.realm: Docker Manager (In Memory Auth)

auth.users:
  - login: admin
    password: admin
    roles:
      - ADMIN

  - login: rolea
    password: rolea
    roles:
      - A

  - login: roleb
    password: roleb
    roles:
      - B

  - login: roleab
    password: roleab
    roles:
      - A
      - B