docker:
  client:
    boot2docker:
      certPath: ~/.boot2docker/certs/boot2docker-vm/
    atld-devtools02.int.aonesolutions.us:
      apiVersion: 1.15

environment:
  configuration:
    location: classpath:/data/env-config


active:
  tiers:
    - development
    - localhost