auth.bypass: false

docker:
  client:
    boot2docker:
      certPath: ~/.boot2docker/certs/boot2docker-vm/
    atld-devtools02.int.aonesolutions.us:
      apiVersion: 1.15

spring.thymeleaf.mode: LEGACYHTML5