docker:
  client:
    boot2docker:
      certPath: ~/.boot2docker/certs/boot2docker-vm/
    atld-devtools02.int.aonesolutions.us:
      apiVersion: 1.15

environment:
  configLocation: classpath:/data/env-config


activeTiers:
  - development
  - localhost