auth.bypass: false
auth.type: AllowAnyone
auth.realm: Docker Manager (Allow Anyone)

docker:
  client:
    boot2docker:
      certPath: ~/.boot2docker/certs/boot2docker-vm/
    192.168.99.100:
      certPath: ~//.docker/machine/machines/default/

spring.thymeleaf.mode: LEGACYHTML5

# Set the session timeout to 1 day
server.session-timeout: 86400

plugins:
  - org.ventiv.docker.manager.plugin.DynatracePlugin
  - org.ventiv.docker.manager.plugin.JavaDebugPlugin
  - org.ventiv.docker.manager.plugin.SlackNotificationPlugin

auth.permissionsToAudit: START, STOP, RESTART, DEPLOY, REMOVE

webjars.requirejs.newModules:
webjars.requirejs.paths.select2: dist/js/select2.min

spring.jpa.hibernate.ddl-auto: update

spring.activiti.processDefinitionLocationPrefix: file:./config/env-config/processes/

# Since we do not use one single Rabbit Connection (it's configured by Jobs), disable health check
management.health.rabbit.enabled: false