auth.bypass: false
auth.type: AllowAnyone
auth.realm: Docker Manager (Allow Anyone)

docker:
  client:
    boot2docker:
      certPath: ~/.boot2docker/certs/boot2docker-vm/
    atld-devtools02.int.aonesolutions.us:
      apiVersion: 1.15

spring.thymeleaf.mode: LEGACYHTML5

# Set the session timeout to 1 day
server.session-timeout: 86400