auth.type: Ldap
auth.realm: AES Domain

ldap:
  server:
    url: ldap://eu_ldap.int.aonesolutions.us:389
    managerDn: CN=rcsvnbind,OU=Service_Accounts,OU=User_Control,OU=eSolutions,DC=int,DC=aonesolutions,DC=us
    managerPassword: Ld4pgtKrb5
  user:
    searchBase: OU=User_Control,OU=eSolutions,DC=int,DC=aonesolutions,DC=us
    searchFilter: (&(objectClass=person)(sAMAccountName={0}))
  group:
    searchBase: OU=Security_Groups,OU=User_Control,OU=eSolutions,DC=int,DC=aonesolutions,DC=us
    searchFilter: (&(objectClass=group)(member={0}))
